### Register User
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "John",
    "email": "johnwickochieng@gmail.com",
    "role": "staff",
    "password": "password",
    "passwordConfirm": "password"
}

### Login User
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "johndoe@.com",
    "password": "password"
}

### Get All Users
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTE0OTQ4ZmE4YmMwZGY1ZTk2ZjJjNCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQyODE3NjIxLCJleHAiOjE3NDI5MDQwMjF9.dxsfLNRXIhIivffZx2ZVpgdTWX8atUwcYi6i-ahcxVQ

### Update User
PUT http://localhost:3000/api/67cec550e5b6179cc92d83f9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2VjNTUwZTViNjE3OWNjOTJkODNmOSIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQxNjA0NTQ0LCJleHAiOjE3NDE2OTA5NDR9.Q3VD8Lnj5jPBwdNv40PfNEciYebOOzBTjPDpPNHLBS

{
    "name": "John Updated",
    "profilePicture": "https://example.com/profile.jpg",
    "bio": "Updated bio",
    "role": "admin",
    "status": "active",
    "is_deleted": false
}

### Soft Delete User
DELETE http://localhost:3000/api/users/67cec550e5b6179cc92d83f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2VjNTUwZTViNjE3OWNjOTJkODNmOSIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQxNjA0NTQ0LCJleHAiOjE3NDE2OTA5NDR9.Q3VD8Lnj5jPBwdNv40PfNEciYebOOzBTjPDpPNHLBS
#### register user
post http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "Brandon",
  "email": "brandon@.com",
  "password": "password",
  "passwordConfirm": "password",
  "role": "student"
}

### login user
post http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "brandon@.com",
    "password": "password"
}



### Create Article
POST http://localhost:3000/api/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTE0OTQ4ZmE4YmMwZGY1ZTk2ZjJjNCIsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQyODE3NjIxLCJleHAiOjE3NDI5MDQwMjF9.dxsfLNRXIhIivffZx2ZVpgdTWX8atUwcYi6i-ahcxVQ

{
    "title": "New Article",
    "body": "This is the content of the new article."
}
